// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RISE.Entity.REPORTTESTDB;

namespace RISE.Entity.Migrations.REPORTTESTDB
{
    [DbContext(typeof(REPORTTESTDBContext))]
    partial class REPORTTESTDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("RISE.Entity.REPORTTESTDB.Report", b =>
                {
                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("UUID");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("RISE.Entity.REPORTTESTDB.ReportDetail", b =>
                {
                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PersonCount")
                        .HasColumnType("integer");

                    b.Property<int>("PhoneNumberCount")
                        .HasColumnType("integer");

                    b.HasKey("UUID", "ReportId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportDetail");
                });

            modelBuilder.Entity("RISE.Entity.REPORTTESTDB.ReportDetail", b =>
                {
                    b.HasOne("RISE.Entity.REPORTTESTDB.Report", "Report")
                        .WithMany("ReportDetails")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("RISE.Entity.REPORTTESTDB.Report", b =>
                {
                    b.Navigation("ReportDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
